# Generated by Django 3.2.5 on 2021-07-29 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
