apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: forum
            - name: POSTGRES_PASSWORD
              value: forum
            - name: POSTGRES_USER
              value: forum
          image: postgres
          name: db
          ports:
            - containerPort: 5432
      restartPolicy: Always
