apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - args:
            - sh
            - -c
            - ' sleep 3 && python manage.py migrate && python manage.py createsuperuser --noinput && python manage.py runserver 0.0.0.0:8000'
          env:
            - name: DJANGO_SUPERUSER_EMAIL
              value: mohmf@mohmf.com
            - name: DJANGO_SUPERUSER_PASSWORD
              value: mohmf
            - name: DJANGO_SUPERUSER_USERNAME
              value: mohmf
          image: mohmf/sary:latest
          name: web
          ports:
            - containerPort: 8000
      restartPolicy: Always
